[package]
name = "metacat"
version = "0.1.2"
edition = "2024"
description = "metacat: a categorical theorem prover"
repository = "https://github.com/statusfailed/metacat"
documentation = "https://docs.rs/metacat"
license = "MIT OR Apache-2.0"

[dependencies]
hexpr = { workspace = true }
open-hypergraphs = { workspace = true }
thiserror = { workspace = true }
