[package]
name = "metacat-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
hexpr = { workspace = true }
open-hypergraphs = { workspace = true }
thiserror = { workspace = true }
anyhow = "1.0.100"
metacat = { version = "0.1.0", path = "../metacat" }

[[bin]]
name = "metacat-cli"
path = "main.rs"
