[package]
name = "metacat-lsp"
version = "0.1.0"
edition = "2024"
description = "Language server for Metacat"
repository = "https://github.com/statusfailed/metacat"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "metacat-lsp"
path = "src/main.rs"

[dependencies]
hexpr = { workspace = true }
metacat = { version = "0.2.2", path = "../metacat" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { workspace = true, features = ["io-std", "macros", "rt-multi-thread"] }
tower-lsp = { workspace = true }
