//! Syntax for finite relations.
//!
//! [`FinRelSignature`] presents finite relations using the four generators of
//! a bicommutative bimonoid. This module currently provides syntax only;
//! interpreting terms as relations or Boolean matrices is left to a later
//! layer.

use hexpr::{Hexpr, Operation, Signature};

/// A generator in the finite-relation signature.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum FinRelOp {
    /// Duplicate one wire: `1 -> 2`.
    Dup,
    /// Merge two wires: `2 -> 1`.
    Sup,
    /// Delete one wire: `1 -> 0`.
    Del,
    /// Select from no wires: `0 -> 1`.
    Sel,
}

/// The single-sorted signature generated by [`FinRelOp`].
#[derive(Clone, Copy, Debug, Default)]
pub struct FinRelSignature;

/// An error encountered while parsing the finite-relation signature.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum FinRelSignatureError {
    /// The operation is not one of `dup`, `sup`, `del`, or `sel`.
    #[error("unknown finite-relation operation `{0}`")]
    UnknownOperation(Operation),
}

impl Signature for FinRelSignature {
    type Arr = FinRelOp;
    type Obj = ();
    type Error = FinRelSignatureError;

    fn try_parse_op(&self, operation: &Operation) -> Result<Self::Arr, Self::Error> {
        match operation.as_str() {
            "dup" => Ok(FinRelOp::Dup),
            "sup" => Ok(FinRelOp::Sup),
            "del" => Ok(FinRelOp::Del),
            "sel" => Ok(FinRelOp::Sel),
            _ => Err(FinRelSignatureError::UnknownOperation(operation.clone())),
        }
    }

    fn try_parse_object(&self, _object: &Hexpr) -> Result<Self::Obj, Self::Error> {
        // FinRel has one generating object, represented internally by `()`.
        Ok(())
    }

    fn profile(&self, operation: &Self::Arr) -> (Vec<Option<Self::Obj>>, Vec<Option<Self::Obj>>) {
        let (arity, coarity) = match operation {
            FinRelOp::Dup => (1, 2),
            FinRelOp::Sup => (2, 1),
            FinRelOp::Del => (1, 0),
            FinRelOp::Sel => (0, 1),
        };
        (vec![Some(()); arity], vec![Some(()); coarity])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hexpr::{parse_hexprs, try_interpret};

    #[test]
    fn generators_have_the_expected_profiles() -> Result<(), Box<dyn std::error::Error>> {
        let signature = FinRelSignature;
        let cases = [
            ("dup", FinRelOp::Dup, 1, 2),
            ("sup", FinRelOp::Sup, 2, 1),
            ("del", FinRelOp::Del, 1, 0),
            ("sel", FinRelOp::Sel, 0, 1),
        ];

        for (name, expected, arity, coarity) in cases {
            let operation = signature.try_parse_op(&name.parse()?)?;
            assert_eq!(operation, expected);
            let (source, target) = signature.profile(&operation);
            assert_eq!(source.len(), arity);
            assert_eq!(target.len(), coarity);
        }
        Ok(())
    }

    #[test]
    fn rejects_unknown_generators() -> Result<(), Box<dyn std::error::Error>> {
        let operation = "unknown".parse()?;
        assert_eq!(
            FinRelSignature.try_parse_op(&operation),
            Err(FinRelSignatureError::UnknownOperation(operation))
        );
        Ok(())
    }

    #[test]
    fn interprets_composite_syntax() -> Result<(), Box<dyn std::error::Error>> {
        let expression = parse_hexprs("({dup _} {_ sup})")?.remove(0);
        let graph = try_interpret(&FinRelSignature, &expression)?;

        assert_eq!(graph.sources.len(), 2);
        assert_eq!(graph.targets.len(), 2);
        Ok(())
    }
}
